### ISSUE TITLE
Download and Git clone fails in windows

### ISSUE THREAD

**Issue by sloboy** [gadenbuie/covid19-florida#18]
When I git clone the project, the source code pulls down but the pdfs and csvs fail to create.  I think it is the colon in the timestamp of the folders.  I know I could spin up a linux vm, but my work computer is windows and is prevented from this due to security policies.

error: invalid path 'pdfs/2020-04-23_16:38:00_EDT/overall_counts.csv'

I am working with Leon County and a local hospital to model covid response and really want access to the daily testing counts that you have been able to parse.

**Comment by gadenbuie** [comment]
ugh. That's annoying and I really should have used a better path name. I'll try to fix that soon.

In the mean time, everything that I've been able to parse from the PDFs ends up in [data/covid-19-florida_pdf_overall_counts.csv](https://github.com/gadenbuie/covid19-florida/blob/master/data/covid-19-florida_pdf_overall_counts.csv) which you can download directly.

Or if possible for your use case, I'd recommend using [data/covid-19-florida_arcgis_summary.csv](https://github.com/gadenbuie/covid19-florida/master/data/covid-19-florida_arcgis_summary.csv) instead ([direct download link](https://raw.githubusercontent.com/gadenbuie/covid19-florida/master/data/covid-19-florida_arcgis_summary.csv)), since that data comes directly from the ArcGIS API with snapshots starting 2020-03-25.

**Comment by sloboy** [comment]
TYTYTY!
