### ISSUE TITLE
covid-19-florida-tests.csv - County Inquiry

### ISSUE THREAD

**Issue by Thunder-Force** [gadenbuie/covid19-florida#2]
Could you add the counties in this file - covid-19-florida-tests.csv  or maybe create covid-19-florida-county-tests.csv, please?

**Comment by gadenbuie** [comment]
I would love to but they've changed the layout several times a day for the last few days and the most recent change has hidden the county-level data in a very "hard to reach" place.

At the moment, I'm trying to at least capture snapshots of all of the changes and if the PDFs are stable then I may end up being able to pull the tables out of them.

If I get the PDF table extraction up and running, it will most likely result in individual `.csv` files for each table in the reports.

Thanks for the issue -- I started working on this because I wanted to ensure that Florida county-level test counts were reported/saved somewhere. The frequent format changes and moving of data has been frustrating but it's good to know I'm not the only one wanting a clean, county-level time series.

I'm going to close this issue but link it to #1 which covers the move to PDFs.
